#----------------------------------------------------------------------------
file(GLOB mc_headers *.hh)
#
#----------------------------------------------------------------------------
install(FILES ${mc_headers} DESTINATION include/montecarlo)
#
#----------------------------------------------------------------------------
