#----------------------------------------------------------------------------
file(GLOB ana_headers *.hh)
#
#----------------------------------------------------------------------------
install(FILES ${ana_headers} DESTINATION include/analysis)
#
#----------------------------------------------------------------------------
