#----------------------------------------------------------------------------
file(GLOB geo_headers *.hh)
#
#----------------------------------------------------------------------------
install(FILES ${geo_headers} DESTINATION include/geometry)
#
#----------------------------------------------------------------------------
