#----------------------------------------------------------------------------
file(GLOB eview_headers *.hh)
#
#----------------------------------------------------------------------------
install(FILES ${eview_headers} DESTINATION include/eventviewer)
#
#----------------------------------------------------------------------------
