#----------------------------------------------------------------------------
file(GLOB digi_headers *.hh)
#
#----------------------------------------------------------------------------
install(FILES ${digi_headers} DESTINATION include/digitizer)
#
#----------------------------------------------------------------------------
